import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { AdminHeading, LoadingRows } from "@/components/admin/AdminUI";
import { getAdminDisputes, resolveAdminDispute } from "@/services/adminService";
import { getErrorMessage } from "@/services/api";
import { formatDateTime, formatNaira } from "@/utils/format";

export const Route = createFileRoute("/admin/disputes")({ component: DisputesPage });
function DisputesPage() {
  const client = useQueryClient();
  const [notes, setNotes] = useState<Record<string, string>>({});
  const { data = [], isLoading } = useQuery({ queryKey: ["admin-disputes"], queryFn: getAdminDisputes });
  const mutation = useMutation({ mutationFn: ({ id, resolution }: { id: string; resolution: "release_to_vendor" | "refund_customer" }) => resolveAdminDispute(id, resolution, notes[id] ?? "Resolved after administrator review."), onSuccess: () => { client.invalidateQueries({ queryKey: ["admin-disputes"] }); client.invalidateQueries({ queryKey: ["admin-overview"] }); toast.success("Dispute resolved and both parties notified"); }, onError: (error) => toast.error(getErrorMessage(error, "Could not resolve dispute")) });
  return <><AdminHeading title="Disputes" description="Review held payments and decide where the funds should go." />{isLoading ? <LoadingRows /> : data.length === 0 ? <div className="rounded-lg border border-dashed border-border bg-card p-12 text-center"><p className="font-semibold">No open disputes</p><p className="mt-1 text-sm text-muted-foreground">New customer disputes will appear here.</p></div> : <div className="space-y-4">{data.map((order) => <section key={order.id} className="rounded-lg border border-border bg-card p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-lg font-bold">{order.orderNumber}</h2><span className="rounded-full bg-destructive/10 px-2 py-1 text-xs font-semibold text-destructive">Payment disputed</span></div><p className="mt-1 text-sm text-muted-foreground">{order.customerName} · {order.storeName} · {formatDateTime(order.escrow?.disputeOpenedAt ?? order.placedAt)}</p><p className="mt-4 text-sm"><span className="font-semibold">Customer reason:</span> {order.escrow?.disputeReason ?? "No reason supplied"}</p><p className="mt-2 text-sm"><span className="font-semibold">Amount held:</span> {formatNaira(order.escrow?.amount ?? order.total)}</p></div><div className="w-full lg:max-w-md"><textarea value={notes[order.id] ?? ""} onChange={(event) => setNotes((current) => ({ ...current, [order.id]: event.target.value }))} placeholder="Add the decision note for both parties" className="min-h-20 w-full rounded-md border border-input bg-background p-3 text-sm" /><div className="mt-2 flex flex-col gap-2 sm:flex-row"><button disabled={mutation.isPending} onClick={() => mutation.mutate({ id: order.id, resolution: "release_to_vendor" })} className="rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50">Release to vendor</button><button disabled={mutation.isPending} onClick={() => mutation.mutate({ id: order.id, resolution: "refund_customer" })} className="rounded-md border border-destructive px-4 py-2 text-sm font-semibold text-destructive disabled:opacity-50">Refund customer</button></div></div></div></section>)}</div>}</>;
}
