/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as VendorRouteRouteImport } from './routes/vendor/route'
import { Route as VendorRegisterRouteImport } from './routes/vendor-register'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDisputesRouteImport } from './routes/admin/disputes'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminVendorsRouteImport } from './routes/admin/vendors'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as CustomerNotificationsRouteImport } from './routes/customer/notifications'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as MessagesConversationIdRouteImport } from './routes/messages/$conversationId'
import { Route as PaymentCallbackRouteImport } from './routes/payment/callback'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as StoreStoreSlugRouteImport } from './routes/store/$storeSlug'
import { Route as VendorIndexRouteImport } from './routes/vendor/index'
import { Route as VendorAnalyticsRouteImport } from './routes/vendor/analytics'
import { Route as VendorCustomersRouteImport } from './routes/vendor/customers'
import { Route as VendorDeliveryRouteImport } from './routes/vendor/delivery'
import { Route as VendorInventoryRouteImport } from './routes/vendor/inventory'
import { Route as VendorNotificationsRouteImport } from './routes/vendor/notifications'
import { Route as VendorPayoutsRouteImport } from './routes/vendor/payouts'
import { Route as VendorSettingsRouteImport } from './routes/vendor/settings'
import { Route as VendorSubscriptionRouteImport } from './routes/vendor/subscription'
import { Route as CustomerOrdersIndexRouteImport } from './routes/customer/orders/index'
import { Route as CustomerOrdersOrderIdRouteImport } from './routes/customer/orders/$orderId'
import { Route as VendorMessagesIndexRouteImport } from './routes/vendor/messages/index'
import { Route as VendorMessagesConversationIdRouteImport } from './routes/vendor/messages/$conversationId'
import { Route as VendorOrdersIndexRouteImport } from './routes/vendor/orders/index'
import { Route as VendorOrdersOrderIdRouteImport } from './routes/vendor/orders/$orderId'
import { Route as VendorProductsIndexRouteImport } from './routes/vendor/products/index'
import { Route as VendorProductsProductIdRouteImport } from './routes/vendor/products/$productId'
import { Route as VendorProductsNewRouteImport } from './routes/vendor/products/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRouteRoute = VendorRouteRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRegisterRoute = VendorRegisterRouteImport.update({
  id: '/vendor-register',
  path: '/vendor-register',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/customer/notifications',
  path: '/customer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/messages/$conversationId',
  path: '/messages/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreStoreSlugRoute = StoreStoreSlugRouteImport.update({
  id: '/store/$storeSlug',
  path: '/store/$storeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRouteRoute,
} as any)
const VendorAnalyticsRoute = VendorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => VendorRouteRoute,
} as any)
const VendorCustomersRoute = VendorCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => VendorRouteRoute,
} as any)
const VendorDeliveryRoute = VendorDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => VendorRouteRoute,
} as any)
const VendorInventoryRoute = VendorInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => VendorRouteRoute,
} as any)
const VendorNotificationsRoute = VendorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => VendorRouteRoute,
} as any)
const VendorPayoutsRoute = VendorPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => VendorRouteRoute,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VendorRouteRoute,
} as any)
const VendorSubscriptionRoute = VendorSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => VendorRouteRoute,
} as any)
const CustomerOrdersIndexRoute = CustomerOrdersIndexRouteImport.update({
  id: '/customer/orders/',
  path: '/customer/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersOrderIdRoute = CustomerOrdersOrderIdRouteImport.update({
  id: '/customer/orders/$orderId',
  path: '/customer/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorMessagesIndexRoute = VendorMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => VendorRouteRoute,
} as any)
const VendorMessagesConversationIdRoute =
  VendorMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => VendorRouteRoute,
  } as any)
const VendorOrdersIndexRoute = VendorOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => VendorRouteRoute,
} as any)
const VendorOrdersOrderIdRoute = VendorOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => VendorRouteRoute,
} as any)
const VendorProductsIndexRoute = VendorProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => VendorRouteRoute,
} as any)
const VendorProductsProductIdRoute = VendorProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => VendorRouteRoute,
} as any)
const VendorProductsNewRoute = VendorProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => VendorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/vendor': typeof VendorRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/vendor-register': typeof VendorRegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wishlist': typeof WishlistRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store/$storeSlug': typeof StoreStoreSlugRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/delivery': typeof VendorDeliveryRoute
  '/vendor/inventory': typeof VendorInventoryRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/payouts': typeof VendorPayoutsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/subscription': typeof VendorSubscriptionRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/vendor/messages/$conversationId': typeof VendorMessagesConversationIdRoute
  '/vendor/orders/$orderId': typeof VendorOrdersOrderIdRoute
  '/vendor/products/$productId': typeof VendorProductsProductIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
  '/vendor/messages/': typeof VendorMessagesIndexRoute
  '/vendor/orders/': typeof VendorOrdersIndexRoute
  '/vendor/products/': typeof VendorProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/vendor-register': typeof VendorRegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wishlist': typeof WishlistRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store/$storeSlug': typeof StoreStoreSlugRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/delivery': typeof VendorDeliveryRoute
  '/vendor/inventory': typeof VendorInventoryRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/payouts': typeof VendorPayoutsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/subscription': typeof VendorSubscriptionRoute
  '/admin': typeof AdminIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/vendor/messages/$conversationId': typeof VendorMessagesConversationIdRoute
  '/vendor/orders/$orderId': typeof VendorOrdersOrderIdRoute
  '/vendor/products/$productId': typeof VendorProductsProductIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/customer/orders': typeof CustomerOrdersIndexRoute
  '/vendor/messages': typeof VendorMessagesIndexRoute
  '/vendor/orders': typeof VendorOrdersIndexRoute
  '/vendor/products': typeof VendorProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/vendor': typeof VendorRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/vendor-register': typeof VendorRegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wishlist': typeof WishlistRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store/$storeSlug': typeof StoreStoreSlugRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/delivery': typeof VendorDeliveryRoute
  '/vendor/inventory': typeof VendorInventoryRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/payouts': typeof VendorPayoutsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/subscription': typeof VendorSubscriptionRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/vendor/messages/$conversationId': typeof VendorMessagesConversationIdRoute
  '/vendor/orders/$orderId': typeof VendorOrdersOrderIdRoute
  '/vendor/products/$productId': typeof VendorProductsProductIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
  '/vendor/messages/': typeof VendorMessagesIndexRoute
  '/vendor/orders/': typeof VendorOrdersIndexRoute
  '/vendor/products/': typeof VendorProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/vendor'
    | '/cart'
    | '/checkout'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/marketplace'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/vendor-register'
    | '/verify-email'
    | '/wishlist'
    | '/admin/disputes'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/security'
    | '/admin/users'
    | '/admin/vendors'
    | '/categories/$slug'
    | '/customer/notifications'
    | '/messages/$conversationId'
    | '/payment/callback'
    | '/product/$slug'
    | '/store/$storeSlug'
    | '/vendor/analytics'
    | '/vendor/customers'
    | '/vendor/delivery'
    | '/vendor/inventory'
    | '/vendor/notifications'
    | '/vendor/payouts'
    | '/vendor/settings'
    | '/vendor/subscription'
    | '/admin/'
    | '/categories/'
    | '/messages/'
    | '/vendor/'
    | '/customer/orders/$orderId'
    | '/vendor/messages/$conversationId'
    | '/vendor/orders/$orderId'
    | '/vendor/products/$productId'
    | '/vendor/products/new'
    | '/customer/orders/'
    | '/vendor/messages/'
    | '/vendor/orders/'
    | '/vendor/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/marketplace'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/vendor-register'
    | '/verify-email'
    | '/wishlist'
    | '/admin/disputes'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/security'
    | '/admin/users'
    | '/admin/vendors'
    | '/categories/$slug'
    | '/customer/notifications'
    | '/messages/$conversationId'
    | '/payment/callback'
    | '/product/$slug'
    | '/store/$storeSlug'
    | '/vendor/analytics'
    | '/vendor/customers'
    | '/vendor/delivery'
    | '/vendor/inventory'
    | '/vendor/notifications'
    | '/vendor/payouts'
    | '/vendor/settings'
    | '/vendor/subscription'
    | '/admin'
    | '/categories'
    | '/messages'
    | '/vendor'
    | '/customer/orders/$orderId'
    | '/vendor/messages/$conversationId'
    | '/vendor/orders/$orderId'
    | '/vendor/products/$productId'
    | '/vendor/products/new'
    | '/customer/orders'
    | '/vendor/messages'
    | '/vendor/orders'
    | '/vendor/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/vendor'
    | '/cart'
    | '/checkout'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/marketplace'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/vendor-register'
    | '/verify-email'
    | '/wishlist'
    | '/admin/disputes'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/security'
    | '/admin/users'
    | '/admin/vendors'
    | '/categories/$slug'
    | '/customer/notifications'
    | '/messages/$conversationId'
    | '/payment/callback'
    | '/product/$slug'
    | '/store/$storeSlug'
    | '/vendor/analytics'
    | '/vendor/customers'
    | '/vendor/delivery'
    | '/vendor/inventory'
    | '/vendor/notifications'
    | '/vendor/payouts'
    | '/vendor/settings'
    | '/vendor/subscription'
    | '/admin/'
    | '/categories/'
    | '/messages/'
    | '/vendor/'
    | '/customer/orders/$orderId'
    | '/vendor/messages/$conversationId'
    | '/vendor/orders/$orderId'
    | '/vendor/products/$productId'
    | '/vendor/products/new'
    | '/customer/orders/'
    | '/vendor/messages/'
    | '/vendor/orders/'
    | '/vendor/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  VendorRouteRoute: typeof VendorRouteRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  VendorRegisterRoute: typeof VendorRegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WishlistRoute: typeof WishlistRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  ProductSlugRoute: typeof ProductSlugRoute
  StoreStoreSlugRoute: typeof StoreStoreSlugRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  CustomerOrdersOrderIdRoute: typeof CustomerOrdersOrderIdRoute
  CustomerOrdersIndexRoute: typeof CustomerOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-register': {
      id: '/vendor-register'
      path: '/vendor-register'
      fullPath: '/vendor-register'
      preLoaderRoute: typeof VendorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/customer/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$storeSlug': {
      id: '/store/$storeSlug'
      path: '/store/$storeSlug'
      fullPath: '/store/$storeSlug'
      preLoaderRoute: typeof StoreStoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/vendor/analytics': {
      id: '/vendor/analytics'
      path: '/analytics'
      fullPath: '/vendor/analytics'
      preLoaderRoute: typeof VendorAnalyticsRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/vendor/customers': {
      id: '/vendor/customers'
      path: '/customers'
      fullPath: '/vendor/customers'
      preLoaderRoute: typeof VendorCustomersRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/vendor/delivery': {
      id: '/vendor/delivery'
      path: '/delivery'
      fullPath: '/vendor/delivery'
      preLoaderRoute: typeof VendorDeliveryRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/vendor/inventory': {
      id: '/vendor/inventory'
      path: '/inventory'
      fullPath: '/vendor/inventory'
      preLoaderRoute: typeof VendorInventoryRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/vendor/notifications': {
      id: '/vendor/notifications'
      path: '/notifications'
      fullPath: '/vendor/notifications'
      preLoaderRoute: typeof VendorNotificationsRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/vendor/payouts': {
      id: '/vendor/payouts'
      path: '/payouts'
      fullPath: '/vendor/payouts'
      preLoaderRoute: typeof VendorPayoutsRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/vendor/subscription': {
      id: '/vendor/subscription'
      path: '/subscription'
      fullPath: '/vendor/subscription'
      preLoaderRoute: typeof VendorSubscriptionRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/customer/orders/': {
      id: '/customer/orders/'
      path: '/customer/orders'
      fullPath: '/customer/orders/'
      preLoaderRoute: typeof CustomerOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders/$orderId': {
      id: '/customer/orders/$orderId'
      path: '/customer/orders/$orderId'
      fullPath: '/customer/orders/$orderId'
      preLoaderRoute: typeof CustomerOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/messages/': {
      id: '/vendor/messages/'
      path: '/messages'
      fullPath: '/vendor/messages/'
      preLoaderRoute: typeof VendorMessagesIndexRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/vendor/messages/$conversationId': {
      id: '/vendor/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/vendor/messages/$conversationId'
      preLoaderRoute: typeof VendorMessagesConversationIdRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/vendor/orders/': {
      id: '/vendor/orders/'
      path: '/orders'
      fullPath: '/vendor/orders/'
      preLoaderRoute: typeof VendorOrdersIndexRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/vendor/orders/$orderId': {
      id: '/vendor/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/vendor/orders/$orderId'
      preLoaderRoute: typeof VendorOrdersOrderIdRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/vendor/products/': {
      id: '/vendor/products/'
      path: '/products'
      fullPath: '/vendor/products/'
      preLoaderRoute: typeof VendorProductsIndexRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/vendor/products/$productId': {
      id: '/vendor/products/$productId'
      path: '/products/$productId'
      fullPath: '/vendor/products/$productId'
      preLoaderRoute: typeof VendorProductsProductIdRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/vendor/products/new': {
      id: '/vendor/products/new'
      path: '/products/new'
      fullPath: '/vendor/products/new'
      preLoaderRoute: typeof VendorProductsNewRouteImport
      parentRoute: typeof VendorRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDisputesRoute: AdminDisputesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface VendorRouteRouteChildren {
  VendorAnalyticsRoute: typeof VendorAnalyticsRoute
  VendorCustomersRoute: typeof VendorCustomersRoute
  VendorDeliveryRoute: typeof VendorDeliveryRoute
  VendorInventoryRoute: typeof VendorInventoryRoute
  VendorNotificationsRoute: typeof VendorNotificationsRoute
  VendorPayoutsRoute: typeof VendorPayoutsRoute
  VendorSettingsRoute: typeof VendorSettingsRoute
  VendorSubscriptionRoute: typeof VendorSubscriptionRoute
  VendorIndexRoute: typeof VendorIndexRoute
  VendorMessagesConversationIdRoute: typeof VendorMessagesConversationIdRoute
  VendorOrdersOrderIdRoute: typeof VendorOrdersOrderIdRoute
  VendorProductsProductIdRoute: typeof VendorProductsProductIdRoute
  VendorProductsNewRoute: typeof VendorProductsNewRoute
  VendorMessagesIndexRoute: typeof VendorMessagesIndexRoute
  VendorOrdersIndexRoute: typeof VendorOrdersIndexRoute
  VendorProductsIndexRoute: typeof VendorProductsIndexRoute
}

const VendorRouteRouteChildren: VendorRouteRouteChildren = {
  VendorAnalyticsRoute: VendorAnalyticsRoute,
  VendorCustomersRoute: VendorCustomersRoute,
  VendorDeliveryRoute: VendorDeliveryRoute,
  VendorInventoryRoute: VendorInventoryRoute,
  VendorNotificationsRoute: VendorNotificationsRoute,
  VendorPayoutsRoute: VendorPayoutsRoute,
  VendorSettingsRoute: VendorSettingsRoute,
  VendorSubscriptionRoute: VendorSubscriptionRoute,
  VendorIndexRoute: VendorIndexRoute,
  VendorMessagesConversationIdRoute: VendorMessagesConversationIdRoute,
  VendorOrdersOrderIdRoute: VendorOrdersOrderIdRoute,
  VendorProductsProductIdRoute: VendorProductsProductIdRoute,
  VendorProductsNewRoute: VendorProductsNewRoute,
  VendorMessagesIndexRoute: VendorMessagesIndexRoute,
  VendorOrdersIndexRoute: VendorOrdersIndexRoute,
  VendorProductsIndexRoute: VendorProductsIndexRoute,
}

const VendorRouteRouteWithChildren = VendorRouteRoute._addFileChildren(
  VendorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  VendorRouteRoute: VendorRouteRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  VendorRegisterRoute: VendorRegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WishlistRoute: WishlistRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  ProductSlugRoute: ProductSlugRoute,
  StoreStoreSlugRoute: StoreStoreSlugRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  CustomerOrdersOrderIdRoute: CustomerOrdersOrderIdRoute,
  CustomerOrdersIndexRoute: CustomerOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
